# Generated by Django 3.0.8 on 2020-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
